const menu = [
  {
    id: 1,
    title: "Poha",
    category: "breakfast",
    price: 30,
    img: "./images/poha.jpg",
    desc: `North India's go-to Breakfast.`,
  },
  {
    id: 2,
    title: "Chhole Bhature",
    category: "lunch",
    price: 80.0,
    img: "./images/chbh.jpg",
    desc: `There's pleasure in every bite;) `,
  },
  {
    id: 3,
    title: "Evergreen Thali",
    category: "lunch",
    price: 130,
    img: "./images/thaali.jpg",
    desc: `Food that's full of surprises.`,
  },
  {
    id: 4,
    title: "Bread Pakora",
    category: "breakfast",
    price: 15,
    img: "./images/b-pakora.jpg",
    desc: `You can't it eat just one.`,
  },
  {
    id: 5,
    title: "Butter Chicken",
    category: "lunch",
    price: 70.0,
    img: "./images/but-chi.jpg",
    desc: `Slice of India on your plate `,
  },
  {
    id: 6,
    title: "Lassi dream",
    category: "shakes",
    price: 20.0,
    img: "./images/lassi.jpg",
    desc: `Drink of power booster `,
  },
  {
    id: 7,
    title: "Biryani",
    category: "lunch",
    price: 110.0,
    img: "./images/biryani.jpg",
    desc: `Biryani- Direct plan to plate. `,
  },
  {
    id: 8,
    title: "Noodles",
    category: "lunch",
    price: 60.0,
    img: "./images/noodles.jpg",
    desc: `Oodles and noodles `,
  },
  {
    id: 9,
    title: "Falooda",
    category: "shakes",
    price: 30.0,
    img: "./images/faaloda.jpg",
    desc: `Make every sip COUNT.`,
  },
];
export default menu;
